### ISSUE TITLE
 failed match_color with average_color : [  0.  82. 244.] and color_tolerance : 5

### ISSUE THREAD

**Issue by DayDr3am3rs420** [Xu-Justin/auto-pokemeow#1]
Any idea how to fix this? new to python sorry... also idk if you'll see this

**Comment by DayDr3am3rs420** [comment]
@Xu-Justin

**Comment by Xu-Justin** [comment]
Hi @DayDr3am3rs420 , could you run the following command and send `panels.png` and `color_panel.png`.

```
python main.py --preview --output_panels panels.png --output_color_panel color_panel.png 
```

Thank you :)

**Comment by DayDr3am3rs420** [comment]
@Xu-Justin C:\Users\jpelk>python main.py --preview --output_panels panels.png --output_color_panel color_panel.png
2023-03-01 09:16:01,165 | INFO: Namespace(run=False, preview=True, config='config.json', output_panels='panels.png', output_color_panel='color_panel.png')
2023-03-01 09:16:01,165 | INFO: input_panel : [400, 990, 500, 1015]
2023-03-01 09:16:01,169 | INFO: color_panel : [385, 700, 386, 850]
2023-03-01 09:16:01,169 | INFO: color - common : [8, 85, 251]
2023-03-01 09:16:01,169 | INFO: color - uncommon : [19, 181, 231]
2023-03-01 09:16:01,169 | INFO: color - rare : [251, 138, 8]
2023-03-01 09:16:01,169 | INFO: color - super_rare : [248, 244, 7]
2023-03-01 09:16:01,169 | INFO: color - legendary : [160, 7, 248]
2023-03-01 09:16:01,169 | INFO: color - shiny_purple : [255, 153, 204]
2023-03-01 09:16:01,169 | INFO: color - captcha : [234, 37, 11]
2023-03-01 09:16:01,169 | INFO: color - discord_background : [54, 57, 63]
2023-03-01 09:16:01,169 | INFO: color - discord_background_dark : [32, 34, 37]
2023-03-01 09:16:01,169 | INFO: color_tolerance : 5
2023-03-01 09:16:01,169 | INFO: ball - pokeball : namespace(name='pokeball', panel=[390, 925, 440, 945], catch_rarity=['common', 'uncommon'])
2023-03-01 09:16:01,173 | INFO: ball - greatball : namespace(name='greatball', panel=[460, 925, 510, 945], catch_rarity=['rare'])
2023-03-01 09:16:01,173 | INFO: ball - ultraball : namespace(name='ultraball', panel=[535, 925, 585, 945], catch_rarity=['super_rare', 'legendary', 'shiny_purple'])
2023-03-01 09:16:01,173 | INFO: ball - masterball : namespace(name='masterball', panel=[605, 925, 655, 945], catch_rarity=[])
2023-03-01 09:16:01,173 | INFO: command - pokemon : ;p
2023-03-01 09:16:01,173 | INFO: kwargs : {'sleep_after_iteration': [7, 20], 'sleep_after_command': [2.0, 2.5], 'sleep_after_move_cursor': [0.5, 2], 'cursor_duration': [0.1, 0.5], 'sleep_after_iteration_preview': 1}

Is this the info you requested?

**Comment by Xu-Justin** [comment]
> @Xu-Justin C:\Users\jpelk>python main.py --preview --output_panels panels.png --output_color_panel color_panel.png
> 2023-03-01 09:16:01,165 | INFO: Namespace(run=False, preview=True, config='config.json', output_panels='panels.png', output_color_panel='color_panel.png')
> 2023-03-01 09:16:01,165 | INFO: input_panel : [400, 990, 500, 1015]
> 2023-03-01 09:16:01,169 | INFO: color_panel : [385, 700, 386, 850]
> 2023-03-01 09:16:01,169 | INFO: color - common : [8, 85, 251]
> 2023-03-01 09:16:01,169 | INFO: color - uncommon : [19, 181, 231]
> 2023-03-01 09:16:01,169 | INFO: color - rare : [251, 138, 8]
> 2023-03-01 09:16:01,169 | INFO: color - super_rare : [248, 244, 7]
> 2023-03-01 09:16:01,169 | INFO: color - legendary : [160, 7, 248]
> 2023-03-01 09:16:01,169 | INFO: color - shiny_purple : [255, 153, 204]
> 2023-03-01 09:16:01,169 | INFO: color - captcha : [234, 37, 11]
> 2023-03-01 09:16:01,169 | INFO: color - discord_background : [54, 57, 63]
> 2023-03-01 09:16:01,169 | INFO: color - discord_background_dark : [32, 34, 37]
> 2023-03-01 09:16:01,169 | INFO: color_tolerance : 5
> 2023-03-01 09:16:01,169 | INFO: ball - pokeball : namespace(name='pokeball', panel=[390, 925, 440, 945], catch_rarity=['common', 'uncommon'])
> 2023-03-01 09:16:01,173 | INFO: ball - greatball : namespace(name='greatball', panel=[460, 925, 510, 945], catch_rarity=['rare'])
> 2023-03-01 09:16:01,173 | INFO: ball - ultraball : namespace(name='ultraball', panel=[535, 925, 585, 945], catch_rarity=['super_rare', 'legendary', 'shiny_purple'])
> 2023-03-01 09:16:01,173 | INFO: ball - masterball : namespace(name='masterball', panel=[605, 925, 655, 945], catch_rarity=[])
> 2023-03-01 09:16:01,173 | INFO: command - pokemon : ;p
> 2023-03-01 09:16:01,173 | INFO: kwargs : {'sleep_after_iteration': [7, 20], 'sleep_after_command': [2.0, 2.5], 'sleep_after_move_cursor': [0.5, 2], 'cursor_duration': [0.1, 0.5], 'sleep_after_iteration_preview': 1}
> 
> Is this the info you requested?

No. Check you folder, are there images with the name `panels.png` and `color_panel.png` ?

**Comment by DayDr3am3rs420** [comment]
> > @Xu-Justin C:\Users\jpelk>python main.py --preview --output_panels panels.png --output_color_panel color_panel.png
> > 2023-03-01 09:16:01,165 | INFO: Namespace(run=False, preview=True, config='config.json', output_panels='panels.png', output_color_panel='color_panel.png')
> > 2023-03-01 09:16:01,165 | INFO: input_panel : [400, 990, 500, 1015]
> > 2023-03-01 09:16:01,169 | INFO: color_panel : [385, 700, 386, 850]
> > 2023-03-01 09:16:01,169 | INFO: color - common : [8, 85, 251]
> > 2023-03-01 09:16:01,169 | INFO: color - uncommon : [19, 181, 231]
> > 2023-03-01 09:16:01,169 | INFO: color - rare : [251, 138, 8]
> > 2023-03-01 09:16:01,169 | INFO: color - super_rare : [248, 244, 7]
> > 2023-03-01 09:16:01,169 | INFO: color - legendary : [160, 7, 248]
> > 2023-03-01 09:16:01,169 | INFO: color - shiny_purple : [255, 153, 204]
> > 2023-03-01 09:16:01,169 | INFO: color - captcha : [234, 37, 11]
> > 2023-03-01 09:16:01,169 | INFO: color - discord_background : [54, 57, 63]
> > 2023-03-01 09:16:01,169 | INFO: color - discord_background_dark : [32, 34, 37]
> > 2023-03-01 09:16:01,169 | INFO: color_tolerance : 5
> > 2023-03-01 09:16:01,169 | INFO: ball - pokeball : namespace(name='pokeball', panel=[390, 925, 440, 945], catch_rarity=['common', 'uncommon'])
> > 2023-03-01 09:16:01,173 | INFO: ball - greatball : namespace(name='greatball', panel=[460, 925, 510, 945], catch_rarity=['rare'])
> > 2023-03-01 09:16:01,173 | INFO: ball - ultraball : namespace(name='ultraball', panel=[535, 925, 585, 945], catch_rarity=['super_rare', 'legendary', 'shiny_purple'])
> > 2023-03-01 09:16:01,173 | INFO: ball - masterball : namespace(name='masterball', panel=[605, 925, 655, 945], catch_rarity=[])
> > 2023-03-01 09:16:01,173 | INFO: command - pokemon : ;p
> > 2023-03-01 09:16:01,173 | INFO: kwargs : {'sleep_after_iteration': [7, 20], 'sleep_after_command': [2.0, 2.5], 'sleep_after_move_cursor': [0.5, 2], 'cursor_duration': [0.1, 0.5], 'sleep_after_iteration_preview': 1}
> > Is this the info you requested?
> 
> No. Check you folder, are there images with the name `panels.png` and `color_panel.png` ?

I dont see any, no. where would they be?

**Comment by DayDr3am3rs420** [comment]
i searched my pc for any images with the name panels.png and color_panel.png and nothing came up, also thank you for taking time to reply to this old post <3 i appreciate it

**Comment by Xu-Justin** [comment]
If you don't mind sharing your email address, i could send you to a google meet link invitation to help resolving ur issue, would you?

**Comment by DayDr3am3rs420** [comment]
@Xu-Justin
